# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ea8a096c9271d200c502c1d5930fa2902e0801b330b50f1d207fcd331523c0bc1ebd26197acc4c3fe8c6da87b76950d2d1ba810fe87af480e0546f1de07834

test:
  secret_key_base: ad2cc4ce283d33e977c48a90c2bb4ffd865f4dcf4255d2c05b9004a91faa26ab174cf6ebad629a5db3efcd81f80c3d6e40086f15198d46a8c5c7560a4c953e82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
